#!/bin/bash
echo loopfiles.sh was generated by the "newbash.sh" script.
# this bash script will take another script as arguement 
# and appy to all files in the directory
#  

# $1 should be the relative path
# $2 permissions level

for file in $(ls $1*.sh);
do
    let i++
    echo chmod $2 $file
    chmod $2 $file
    #echo "bash script $file"
done
echo The number of bash scripts in this directory is $i