#!/bin/bash

if [ $# -ge 3 ]
then
    echo "Please enter the shell name as the first argument, no need for \".sh\""
    echo "If there is a specific directory in which it should be places, add relative or compelete dir path as second arguement"
    exit 1

elif [ -f $2$1.sh ]
then
    echo "shell $1.sh already exists in this directory, please choose another name or delete.
    this bash script will NOT overwrite existing files."
    exit 1
elif [ $# -eq 2 ]
then
    echo "generating new sample shell $1"
    touch $1.sh # create file 
    echo "#!/bin/bash" > $1.sh # add shebang
    echo "echo $1 was generated by the \"newbash.sh\" script." >> $1.sh # add shebang
    chmod 755 $1.sh # make it executable
    echo "new shell created, just add code"
    mv ./$1.sh $2
    exit 0
else
    echo "generating new sample shell $1"
    touch $1.sh # create file 
    echo "#!/bin/bash" > $1.sh # add shebang
    echo "echo $1 was generated by the \"newbash.sh\" script." >> $1.sh # add shebang
    chmod 755 $1.sh # make it executable
    echo "new shell created, just add code"
    mv ./$1.sh $2
    exit 0
fi